#!/bin/bash

#SBATCH --job-name=slurm_job
#SBATCH --partition=veryshort
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=28
#SBATCH --cpus-per-task=1
#SBATCH --time=0:20:00
#SBATCH --mem-per-cpu=1000M

echo 'Slurm Job'
module purge
module load OpenMPI/2.0.2-GCC-6.3.0-2.27
  

#export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so


which mpirun
which ./pb_mpi
mpirun  -np 28 ./pb_mpi -d 35_noEF2/35_noEF2.phylip -cat -gtr -x 1 2 35_noEF2/35_noEF2.tree
