#!/bin/bash

#SBATCH --job-name=slurm_job
#SBATCH --partition=cpu_test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=28
#SBATCH --cpus-per-task=1
#SBATCH --time=0:20:00
#SBATCH --mem-per-cpu=1000M

echo 'Slurm Job'
module purge

module load apps/phylobayes/1.8.intel
#module load languages/intel/2017.01
#export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so


which mpirun
which mpiicpc

time mpirun  -np 28  pb_mpi -d 35_noEF2/35_noEF2.phy -f -x 1 2 35_noEF2/35_noEF2.tree
